-- MySQL Script generated by MySQL Workbench
-- Wed Aug 21 00:04:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema E-commerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `E-commerce` DEFAULT CHARACTER SET utf8;
USE `E-commerce`;

-- -----------------------------------------------------
-- Table `E-commerce`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(100) NOT NULL,
  `cpfCliente` CHAR(11) NOT NULL,
  `senhaCliente` VARCHAR(100) NOT NULL,
  `emailCliente` VARCHAR(100) NOT NULL,
  `telefoneCliente` VARCHAR(15) NOT NULL,
  `enderecoCliente` VARCHAR(255) NOT NULL,
  `nascimentoCliente` DATE NOT NULL,
  `sexoCliente` CHAR(1) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `cpfCliente_UNIQUE` (`cpfCliente` ASC),
  UNIQUE INDEX `emailCliente_UNIQUE` (`emailCliente` ASC),
  UNIQUE INDEX `telefoneCliente_UNIQUE` (`telefoneCliente` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `E-commerce`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `nomeAdministrador` VARCHAR(100) NOT NULL,
  `cpfAdministrador` CHAR(11) NOT NULL,
  `senhaAdministrador` VARCHAR(100) NOT NULL,
  `emailAdministrador` VARCHAR(100) NOT NULL,
  `telefoneAdministrador` VARCHAR(15) NOT NULL,
  `enderecoAdministrador` VARCHAR(255) NOT NULL,
  `nascimentoAdministrador` DATE NOT NULL,
  `sexoAdministrador` CHAR(1) NOT NULL,
  `idFuncionario` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  UNIQUE INDEX `cpfAdministrador_UNIQUE` (`cpfAdministrador` ASC),
  UNIQUE INDEX `emailAdministrador_UNIQUE` (`emailAdministrador` ASC),
  UNIQUE INDEX `telefoneAdministrador_UNIQUE` (`telefoneAdministrador` ASC),
  UNIQUE INDEX `idFuncionario_UNIQUE` (`idFuncionario` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `E-commerce`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(100) NOT NULL,
  `categoriaProduto` VARCHAR(50) NOT NULL,
  `validadeProduto` DATE NULL,
  `pesoProduto` FLOAT NULL,
  `valorProduto` DECIMAL(10,2) NOT NULL,
  `estoqueProduto` INT NOT NULL,
  PRIMARY KEY (`idProduto`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `E-commerce`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `dataPedido` DATETIME NOT NULL,
  `statusPedido` VARCHAR(20) NULL,
  `valorTotalPedido` DECIMAL(10,2) NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  -- Removed idAdministrador column
  INDEX `fk_Pedido_cliente_idx` (`idCliente` ASC),
  CONSTRAINT `fk_Pedido_cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `E-commerce`.`ItemPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ItemPedido` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `quantidadeItem` INT NOT NULL,
  `valorUnitarioItem` DECIMAL(10,2) NOT NULL,
  `idPedido` INT NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`idItem`),
  INDEX `fk_ItemPedido_Pedido_idx` (`idPedido` ASC),
  -- REMOVED fk_ItemPedido_Produto
  CONSTRAINT `fk_ItemPedido_Pedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `E-commerce`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `formaPagamento` VARCHAR(20) NOT NULL,
  `parcelasPagamento` INT NULL,
  `descontoPagamento` DECIMAL(5,2) NULL,
  `idPedido` INT NOT NULL,
  PRIMARY KEY (`idPagamento`),
  INDEX `fk_Pagamento_Pedido_idx` (`idPedido` ASC),
  CONSTRAINT `fk_Pagamento_Pedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `E-commerce`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Avaliacao` (
  `idAvaliacao` INT NOT NULL AUTO_INCREMENT,
  `notaAvaliacao` INT NULL,
  `comentarioAvaliacao` TEXT NULL,
  `dataAvaliacao` DATETIME NULL,
  `idCliente` INT NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`idAvaliacao`)
  -- REMOVED fk_Avaliacao_cliente
  -- REMOVED fk_Avaliacao_Produto
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `E-commerce`.`TrocaDevolucao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrocaDevolucao` (
  `idTrocaDevolucao` INT NOT NULL AUTO_INCREMENT,
  `tipoTrocaDevolucao` VARCHAR(10) NOT NULL,
  `dataSolicitacaoTrocaDevolucao` DATE NOT NULL,
  `statusTrocaDevolucao` VARCHAR(20) NOT NULL,
  `idPedido` INT NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`idTrocaDevolucao`),
  INDEX `fk_TrocaDevolucao_Pedido_idx` (`idPedido` ASC),
  -- REMOVED fk_TrocaDevolucao_Produto
  CONSTRAINT `fk_TrocaDevolucao_Pedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
